### ISSUE TITLE
Extremely slow compilation time due to type instabilities

### ISSUE THREAD

**Issue by fredrikekre** [ajt60gaibb/FastGaussQuadrature.jl#47]
On julia 0.6:

```julia
julia> @time gausslobatto(2);
  7.649899 seconds (9.86 M allocations: 451.546 MiB, 4.05% gc time)
```

On 0.5 it is about 3.5 seconds. Some quick debugging with `@code_warntype` suggests the problem is in [this method](https://github.com/ajt60gaibb/FastGaussQuadrature.jl/blob/f6b50605f6bb6e27167f37f7211fb089d4aa9e47/src/gaussjacobi.jl#L369-L385) with the following return type as a result: `Tuple{Union{Array{Complex{Float64},1}, Array{Float64,1}},Union{Array{Complex{Float64},1}, Array{Float64,1}}}`

**Comment by dlfivefifty** [comment]
I'm guessing the issue is that `eig` called on a `Matrix` is not type stable.
 
This should be calling `eig` on a `SymTridiagonal`

**Comment by ajt60gaibb** [comment]
Yes, I agree. See #31.

**Comment by dlfivefifty** [comment]
I fixed the type stability, though it didn't improve the compilation time by much.  But slow compilation is a known bug in the 0.6 betas.

**Comment by fredrikekre** [comment]
Nice! Was about to push an update but you were faster :)
Yea, the compilation time is still a problem. Digging a bit further:

```julia
julia> @time FastGaussQuadrature.JacobiAsy(101,1., 1.)
  6.638096 seconds (5.96 M allocations: 270.349 MiB, 1.98% gc time)
```

**Comment by dlfivefifty** [comment]
Ah, given the other issue had been here for almost a year, I was expecting it to be a race 😉

You’ll see in my code I needed to type assert `::Vector{Float64}`, as `cat` wasn't type inferring correctly (in 0.5).  There is also an unnecessary allocation, so a better solution may be 

```julia
aa = Array{Float64}(n)
aa[1]                  = (b - a)/(2 + ab)
view(aa,2:n-1) .=  (b^2 - a^2)./((abi - 2).*abi)
aa[end]             = (b^2 - a^2)./((2*n - 2+ab).*(2*n+ab))
```

If you are looking into it further, I'll leave it to you to try that change.

**Comment by fredrikekre** [comment]
Yea, I did it with a for-loop instead. I will try to fix some more later and make a PR if I can improve the compilation time

**Comment by KristofferC** [comment]
On 0.7.

```
julia> @time FastGaussQuadrature.JacobiAsy(101,1., 1.)
 28.552633 seconds (61.87 M allocations: 2.746 GiB, 4.82% gc time)
```

**Comment by dlfivefifty** [comment]
This is compile time right? Is it really an issue with this package, or with Julia’s compiler?

**Comment by KristofferC** [comment]
Yes, compile time; just posting an update. Seems the code here is written in a way that interacts badly with the compiler but yeah, the compiler should improve.

**Comment by KristofferC** [comment]
I think the large dotted expressions is a problem for the compiler.  A workaround might be to not use the `@.` macro so much and use normal operators between scalars and only dot operators between arrays.

**Comment by timueh** [comment]
I also noticed a big increase in compilation time going from Julia 0.6 to Julia 0.7. Is there any remedy ahead?

**Comment by hyrodium** [comment]
Current `master` branch on Julia 1.5:
```julia
julia> using FastGaussQuadrature

julia> t = time(); gausslobatto(2); time() - t
7.010434865951538
```

```julia
julia> using FastGaussQuadrature

julia> t=time(); FastGaussQuadrature.jacobi_asy(101,1., 1.); time() - t
5.734845161437988
```
Not as much compilation time as on Julia 0.7, but there may be still a problem.

**Comment by dlfivefifty** [comment]
Note KristofferC seemed to think the issue is the large broadcasted line

https://github.com/JuliaApproximation/FastGaussQuadrature.jl/blob/5506f5fde7c7f3098c1007140af6eb8105c0f5ec/src/gaussjacobi.jl#L205

probably this whole function should be de-MATLABed so it doesn't allocate so much
